name: Primary

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Validate CloudFormation template
        run: |
          aws cloudformation validate-template \
            --template-body file://./infra/template.yml \
            --region ${{ secrets.AWS_REGION }}

      - name: Deploy Infrastructure for SES
        run: |
          STACK_NAME=openbrighton-main-ses
          aws cloudformation deploy \
            --stack-name $STACK_NAME \
            --template-file ./infra/template.yml \
            --no-fail-on-empty-changeset \
            --region ${{ secrets.AWS_REGION }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Build SES Email Templates
        run: npm run build:templates

      - name: Sync SES Email Templates
        run: |
          find templates -type f -name '*.json' | while read template; do
            if [ -f "$template" ]; then
              aws ses create-template --cli-input-json file://$template --region ${{ secrets.AWS_REGION }} || \
              aws ses update-template --cli-input-json file://$template --region ${{ secrets.AWS_REGION }}
            fi
          done
