name: Primary

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Validate CloudFormation template
        run: |
          aws cloudformation validate-template \
            --template-body file://./infra/template.yml \
            --region ${{ secrets.AWS_REGION }}

      - name: Deploy Infrastructure for SES
        run: |
          STACK_NAME=openbrighton-main-ses
          aws cloudformation deploy \
            --stack-name $STACK_NAME \
            --template-file ./infra/ses.yml \
            --no-fail-on-empty-changeset \
            --region ${{ secrets.AWS_REGION }}
